### ISSUE TITLE
ep_draw integration with etherpad-lite

### ISSUE THREAD

**Issue by psymin** [JohnMcLear/ep_draw#28] opened 2020-05-09 16:52 UTC
The installations of ep_draw and etherpad-lite work well for me.

When I enable ep_draw within etherpad, I have an issue with ep_draw only displaying the top bit of the document.

Etherdraw: (http://ip:9002)
![etherdraw-clip](https://user-images.githubusercontent.com/326578/81479733-60bf2f00-91e2-11ea-8ffe-0d1a7c9819c7.png)

Etherpad w/ Etherdraw: (http://ip:9001)
![etherpad-etherdraw-clip](https://user-images.githubusercontent.com/326578/81479732-5f8e0200-91e2-11ea-9070-4bed6a02eb8c.png)
Both are current from git as of yesterday.  Ubuntu 20.04

If anyone has input as to what I'm doing incorrectly, I'd love to hear :)

**Comment by JohnMcLear** [comment] 2020-05-09 17:06
@seballot is on with this

**Comment by seballot** [comment] 2020-05-12 15:21
am I? :) hopefully I will find some time for this ! but not sure

**Comment by JohnMcLear** [comment] 2020-05-12 17:08
Yeah you asked me for details and I sent them to you via email afaik!

**Comment by JohnMcLear** [comment] 2020-05-16 09:13
any progress w/ safari and this @seballot ?

**Comment by JohnMcLear** [comment] 2020-05-16 09:14
btw this was a duplicate of https://github.com/JohnMcLear/ep_draw/issues/27

**Closed by JohnMcLear** 2020-05-16 09:14 UTC

**Comment by cbautista4000** [comment] 2020-05-20 20:15
guys, issue still persist while using google chrome and firefox. could you please take a look into it one more time? thank you so much.
![image](https://user-images.githubusercontent.com/65682887/82492934-0dd45a00-9ab5-11ea-8a2e-d86da8211f97.png)

**Comment by JohnMcLear** [comment] 2020-05-20 22:25
Git pull latest version and clear cache.  99% sure it's fixed.

**Comment by Sayao32** [comment] 2020-05-23 09:10
Hello, I'm having this issue too even with the latest downloaded 3 days ago (last modifications 7 days ago so I assume its the lastest).

What cache are you talking about, browser ? If yes I have the same issue even on a computer who's never used it.

Thanks for your help :)
![image](https://user-images.githubusercontent.com/65808590/82726664-f16b3400-9ce5-11ea-8fe1-98773c8f50f1.png)

**Comment by JohnMcLear** [comment] 2020-05-23 10:16
You might need to update Etherpad to latest ``develop``, not sure tbh!

**Comment by Sayao32** [comment] 2020-05-25 13:26
Hello, still no luck with develop :( the height is not resizing.

![image](https://user-images.githubusercontent.com/65808590/82816775-0984b400-9e9c-11ea-9fca-7b614f32b3d9.png)

**Comment by Sayao32** [comment] 2020-05-26 19:23
Working great with lastest update :) Thanks a lot for your work !
